# Generated by Django 3.2.3 on 2021-05-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='시 쓴 사람')),
                ('title', models.CharField(max_length=200, verbose_name='시 제목')),
                ('text', models.TextField(verbose_name='시 본문')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnailImages/')),
                ('backgroundImg', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='VisitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='이름')),
                ('text', models.TextField(verbose_name='내용')),
                ('phone', models.IntegerField(blank=True, default=False, null=True, verbose_name='전화번호')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
