# Generated by Django 3.2.3 on 2021-07-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sioreum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitform',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='전화번호'),
        ),
    ]
