# Generated by Django 3.2.3 on 2021-07-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sioreum', '0003_auto_20210709_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_color',
            field=models.BooleanField(default=False, verbose_name='글씨 흰색 여부'),
        ),
        migrations.AlterField(
            model_name='post',
            name='backgroundImg',
            field=models.ImageField(blank=True, null=True, upload_to='sioreum/static/sioreum/img/Images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sioreum/static/sioreum/img/thumbnailImages/'),
        ),
    ]
