# Generated by Django 3.2.3 on 2021-07-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sioreum', '0004_auto_20210711_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background',
            field=models.BooleanField(default=False, verbose_name='검정 배경 적용 여부'),
        ),
    ]
