# Generated by Django 3.2.3 on 2021-08-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sioreum', '0005_post_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='backgroundImg',
            field=models.ImageField(blank=True, null=True, upload_to='img/Images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='img/thumbnailImages/'),
        ),
    ]
